name: base32
version: 2.0.0-nullsafety.1
description: Base32 Encoder and Decoder for Dart, primarily used for One Time Password secrets.
homepage: https://github.com/Daegalus/dart-base32
environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  convert: "^3.0.0-nullsafety"
dev_dependencies:
  pedantic: ">=1.9.0"
  test: ^1.16.0-nullsafety
dependency_overrides:
 convert: ^3.0.0-nullsafety
 crypto:
    git:
      url: https://github.com/dart-lang/crypto.git
      ref: "master"
 logging: ^1.0.0-nullsafety